### ISSUE TITLE
Is it possible to persist Websocket connection post callback function?

### ISSUE THREAD

**Issue by ayman-albaz** [status-im/nim-websock#117]
Hello, I'm currently following the example code in the repo, and I noticed that if you were to store the websocket after the callback function ends, the websocket closes (even when the HTTPServer is still alive). The reason for wanting to work outside the callback function is because I need multiple websockets to work in sync, so in my setup I'd like for example 3 websockets to be created first, before moving on to downstream tasks. There would be a seperate background async task coordinating the above.

My fix around for this is to just keep the callback function alive with `asyncSleep` as follows.

```nim
    # Connection is just a wrapper around WSServer and WSSession
    let connection = await newConnection(httpRequest)
    self.registerConnection(connection)  # This just adds the websocket to an array to we can use it for later
    # I need the while loop below to prevent the websocket from closing after callback termination
    while connection.isOpen():
      await sleepAsync(1.seconds)
```
My questions are:
1. Is it possible to persist websocket connection post callback function?
2. If (1) is not possible and the only way to do it is via my example above, would you know of any issues that could arise from keeping a multiple websocket connections (1-500) alive using this method

**Comment by Menduist** [comment]
Indeed in it's current form, the callback needs to wait for the connection to be closed.
You have a few options here:
Your method works, but can be slightly improved:
```nim
    # connection being a WSSession
    await connection.stream.reader.join()
```
The overhead of having a few async procedures waiting for close should be minimal

Another option is to use a custom accept loop instead of the callback, like in `examples/server.nim`
Or, you can a PR to modify somehow the library to enable your use case, but that would require some thinking

**Comment by ayman-albaz** [comment]
Awesome :)

Thanks once again for your help.
