### ISSUE TITLE
Accept timeout

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-websock#79]
Yes, by the time we've got to `handleRequest` we've already read all the data (since it's an HTTP request and headers aren't streamed), but we can still have a malicious attacker simply not finishing writing the headers, so I think a timeout when reading headers would be appropriate - this however should go in `nim-ws`.

_Originally posted by @dryajov in https://github.com/status-im/nim-libp2p/pull/593#discussion_r658940877_

**Comment by arnetheduck** [comment]
It's a bit of an open question where timeouts should go, in an `async` world - ie one can put lots of small timeouts everywhere in each step, or a single timeout in the outer, high-level operation which in turn cancels the steps - the latter means that "connect to peer" should take no longer than N seconds, no matter how many steps are involved, and is often appropriate.

**Comment by arnetheduck** [comment]
In particular, imagine setting a 10s timeout on "read bytes from socket" - obviously this doesn't make sense, because a malicious client can trickle bytes one by one effectively disabling the timeout - in such a case, it makes much more sense that "perform handshake" has the timeout.

**Comment by dryajov** [comment]
It makes sense to have a failsafe timeout on `parseRequest`, otherwise an attacker can send a connection but never finish sending the headers.

Doing this at the application level (for example when calling `accept`) is much harder, because you don't really know where in the accept flow it's stuck and it breaks the fundamental assumption with`accept` in that it only returns when it's ready. 

I agree that timeouts are tricky and it's usually better to allow the application to handle that, but in this case it really is very hard to do with the `accept` that this module exposes. 

For example:

```nim
while true:
  let s = await ws.accept().wait(1.seconds)
```

Doesn't make much sense.

**Comment by dryajov** [comment]
The other way around would be to expose `parseRequest`, but it's a bit to extreme IMO.

**Comment by Menduist** [comment]
To add to this, another issue is that on failure, https://github.com/status-im/nim-websock/blob/a697e3585d583ab6b91a159ea7d023461002c927/websock/http/server.nim#L196 can also block the loop for an unknown amount of time (by just using `nc 127.0.0.1 [wss port]`, the request will block the accept loop for the 2 minutes of the header timeout, **and** after that block indefinitively during the closeWait)

**Comment by rshiv** [comment]
should the goal then be to handle the timeout in accept caller , for e.g

https://github.com/status-im/nim-websock/blob/a697e3585d583ab6b91a159ea7d023461002c927/examples/server.nim#L64,

rather adding timeout in intermediary steps?

**Comment by rshiv** [comment]
As, this issue is identified as a bug for nim-libp2p hence in nim-waku, a minimal solution for the same , would be to add a timeout by the caller. LMKWYT @Menduist.

**Comment by Menduist** [comment]
This is not possible.
Accepting itself can take a long time (because we have to wait for someone to connect to us)

So everything after accept:
https://github.com/status-im/nim-websock/blob/a697e3585d583ab6b91a159ea7d023461002c927/websock/http/server.nim#L174-L197
Must have a timeout



The longer term solution would be to handle multiple incoming requests instead of blocking the accept loop for a single one

**Comment by dryajov** [comment]
There shouldn't be any issues adding a timeout to `parseRequest`. 

> The longer term solution would be to handle multiple incoming requests instead of blocking the accept loop for a single one

This should be something that the calling application handles. If there is a need to handle multiple accepts then the application should "spawn" those itself. The point of `accept` is to give tight control over the incoming connection flow and allow the consuming application decide what level of concurrency it wants. As an alternative `[Tls]HttpServer` take a `handler` callback that will be triggered on any incoming connection. 

The issue being discussed here is that any peer can block during the negotiation process and thus block the entire accept loop, this is a problem if there is only one accept running, but as mentioned above it is by design. The way to address it is to spawn multiple concurrent accepts and perhaps add a more aggressive timeout to the entire `parseRequest`.

If an application wants to handle concurrent incoming connections with accept it should do something like:

```nim
var acceptFuts: seq[Future[HttpRequest]]

for i in 0..<100:
  acceptFuts.add(ws.accept())

while true:
  if self.acceptFuts.len <= 0:
    self.acceptFuts = self.servers.mapIt(it.accept())

  let
    finished = await one(self.acceptFuts)
    index = self.acceptFuts.find(finished)

  self.acceptFuts[index] = self.servers[index].accept()


```
